//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InjectionPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string SecretPassword { get; set; }
        public string FullName { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public int GroupId { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
